apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: arielrahamim/wideops-nodeapp:1.0.0
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: myapp-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
spec:
  selector:
    app: myapp
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: 34.165.71.87.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myapp-svc
            port:
              number: 3000
  tls: 
  - hosts:
      - 34.165.71.87.nip.io
    secretName: mysecret
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-configmap
data:
  MONGO_URI: mongodb://10.0.0.4:27017,10.0.0.3:27017,10.0.0.2:27017/NodeApp?replicaSet=rs0
  APP_PORT: "3000"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: ContainerResource
    containerResource:
      name: cpu
      container: myapp
      target:
        type: Utilization
        averageUtilization: 40
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: kubernetes.io/tls
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURHVENDQWdFQ0ZITmdWbWNHTTVrdTd0YUs2
    VUF4akdUT0Fvb1ZNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1Fa3gKQ3pBSkJnTlZCQVlUQWtsTU1ROHdE
    UVlEVlFRSURBWkpjM0poWld3eEN6QUpCZ05WQkFjTUFrbE1NUnd3R2dZRApWUVFEREJNek5DNHhO
    alV1TnpFdU9EY3VibWx3TG1sdk1CNFhEVEl6TVRJeU9ERTBNakUxT0ZvWERUSTBNREV5Ck56RTBN
    akUxT0Zvd1NURUxNQWtHQTFVRUJoTUNTVXd4RHpBTkJnTlZCQWdNQmtsemNtRmxiREVMTUFrR0Ex
    VUUKQnd3Q1NVd3hIREFhQmdOVkJBTU1Fek0wTGpFMk5TNDNNUzQ0Tnk1dWFYQXVhVzh3Z2dFaU1B
    MEdDU3FHU0liMwpEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNLQnB4bXdINnVhUGcwY3dLMTRR
    eVA0aWdPL3BBc3M0Z1lGb0l3CkxVSmdvMFdvSG5qNXg3NW8xNFUrVm15SDU3eXhzQTdOYXQxOXRv
    RlplTWZOSWtrRHNka2o0Q1kvZTh2NUhrLzcKSGRzRlFURGkxNy9QU3JmZG94c3N0MnQvVlJGVmNp
    REZHWUZReU1WTnlDbENuY2ZUeHNyaFVpT094dDdobitjZQpWaEJ6b0VKaTR0TUNZSVdFMXhidlYy
    TGI3ZzYrY2RFVmlhU2UrT0VmYmlIcWZjMDZKR08ya1c3ajlrUmtVbFM4ClE0UjFHZmQ5NWtlTVNY
    S1gyRkNDbGp4aHZiZWdHWU0zYzMyRUgrSlZCUGJicFYvTmRmM0dkYXc1RTZVZU8yZDkKSldBZTBk
    VHZENDdIeGgvSlpYMXNzNUhHUnBaTzlzUEpOaEVCLzdFN3g2Vzdsc0pCQWdNQkFBRXdEUVlKS29a
    SQpodmNOQVFFTEJRQURnZ0VCQUIyUEpRWFJRTGNzTmZrMCttOW9zUFpXT1lJWHNtam1nMFlRSEdY
    eDJIQWtnbStzCmZiWVl0bUU0ZHNvL25Pd05RS1dMS3lpTlUyV0JoUldVUVJ2SkJCZjFsbGhwZnlk
    NXB1Z3R3Tk5LMXNBSzBQVnoKTk9PWFgzbUE3OTg2SHF2QVlSdS9Qa0xyeXk3ais0OTNvT0grVnM3
    RVptV0NneWxxSE43N0ZGYVhpOFNjcFp0dApuUmJYSG4xbURyMnd0WDQxcEVUWEp6UjhxcG44dEYy
    THhUTE1QLzI1aG1TVkUyZUs3SGJQQ3RIK1hlWDFrcWZmCkc5S1ROWE5oSyt4QVNNcUtGVWUwdjlS
    L0ZydWgvTS9mTnk1anQ1NnBXMkcrVTUxL0g1WHgzdFFrWno2ZCtTaUoKRHhkQzgwa2k0SktKRTJu
    RTYwQWNJOUVrbmlWM05ndnZYTGFSNkxnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktZd2dnU2lBZ0VBQW9JQkFRQ0tCcHhtd0g2dWFQZzAKY3dLMTRReVA0aWdPL3BBc3M0Z1lG
    b0l3TFVKZ28wV29Ibmo1eDc1bzE0VStWbXlINTd5eHNBN05hdDE5dG9GWgplTWZOSWtrRHNka2o0
    Q1kvZTh2NUhrLzdIZHNGUVREaTE3L1BTcmZkb3hzc3QydC9WUkZWY2lERkdZRlF5TVZOCnlDbENu
    Y2ZUeHNyaFVpT094dDdobitjZVZoQnpvRUppNHRNQ1lJV0UxeGJ2VjJMYjdnNitjZEVWaWFTZStP
    RWYKYmlIcWZjMDZKR08ya1c3ajlrUmtVbFM4UTRSMUdmZDk1a2VNU1hLWDJGQ0NsanhodmJlZ0dZ
    TTNjMzJFSCtKVgpCUGJicFYvTmRmM0dkYXc1RTZVZU8yZDlKV0FlMGRUdkQ0N0h4aC9KWlgxc3M1
    SEdScFpPOXNQSk5oRUIvN0U3Cng2Vzdsc0pCQWdNQkFBRUNnZ0VBQUpSMDFLcXdFL2dEMWNBdHdN
    bGZuM3p2bk5tM0RkdHRDMmVxQVVPMm5hR2cKWWI3TGJqbWhLcDlNeWQxcE1RWDhldElKNVJVbU5j
    aU9FUkpSWTJLemNPNnV6d1VnN0FLby9tRm5rcmpHUFkwUAp0NnQ0citMc1ZGY2NQcEdBZy9oOXh1
    Y1R6VVQrNmRnZ2dIMkNXYXR6aVc0WTFwNDJyZTZLRWhhMVFDRTZpaXFlCnJSMzJVMk1naDlyeTcy
    UzNSeWVzdkFQRFEwbWx5RmV0ekFBQU1VOFVaSFJKREVwdWJ4SHkvRGZpRmlDVXlTM3kKNW9rNlhB
    UjQweWV1OVVWVFp6dXprMHRxTnBIUUJodEo5WGM4RG1RcWZ2UlBTbnR5cHRmNkdVdTdCbUsyeTlR
    dwo4ZG15VXhYVDVzSkNpS3ExRGNHRmVMaWI1aUdYMjQ0RnQ5OWVuM0JyVlFLQmdRREFONEFIWEx6
    cG1rcUFWVXFVCm5mMGZUUTVhNlRzTVNhaS9rTEhGbXVpcXdOVkR5cDJRUFhKTldHYlFJR0UxdXdp
    Rk9rdS9TOC9heFF2MGRjbTEKRzhKWjhVWDNFNVRQVkd0RndIUFRqMXJMazA2TDdLUkZhWlFMWFVD
    VHVqOU04ako5elkwV1hxOVZSR1N3bDdzbApKVGhWYldPVVlMRVFnODhhRTFMMmtvc3p4UUtCZ1FD
    MzA2MVIybjNNanFvcG1UWllNWjZxR0Y2eHhLSUU0MUZsClpwTG0xTDY5R2l3ZVVTQTl3cEFBQUk5
    c25NQTRpdjNrNmMvbkZvL0dNUkNXMmVsVDJlV2FOalFYblFrZzVZeEwKTGJMcHVWUFhlVkxlQ0N6
    YTVRcWFBdmFIK1VCZVFabDJEVmU1N1ROd1pTWkdYbVJra3lJSDhVSkh4clZEMm52VQpramt2bytw
    d1RRS0JnR09BMTQvNEcvczUyZk5STThoM2VMOHBYcE1GUllINDU1Z3pTVE9vRzJXNWFTMHN5Q0FS
    CkR3aW5DS0laQVBtVmxyV1JGZ0V6TjZoaWRPdlp4Yzh4VFl6Tjc1QVYzT1R2S0pEMUxZQ0pKMUZY
    TWtRUS9vREkKUk5FVk53YkNWVjU1eWxXQmdOWGhzaFlMejZ2eS8vZ2NxbXJlczd2dHlmdG9vRjg1
    UGF0UzlTaVpBb0dBQU9GNAp3UjJrNEtnR1ZMQ3hPL2J3NWF1OE9HblN4T2M1NnB4MU03bnRPQWE2
    RTJNY0htK2lOUDNMc2grR0pEODJQRFNLCmxIYmROWHZpc25aVTBkd0haNWUrNUNZU2R4L2liakhI
    MjZyUnBnU2t5ditMQjNsMWRZdHlGdkN3eUVMVU0yYVkKOXdFVjhBSHNEd1pBd09LYmxTSW95U05B
    bHhTaTV6L1VHbEJVdlRrQ2dZQkV5SEc2UXlGQXg2bHFCeHVERlc1OQprUWE1dTZHckQ4NlZxT2hh
    YndCMW8xNUZDWTRsT3ovN3hvQnBtNExWbTJKWnZqdG9CNGd2Qm9QRW9EN2xUQVJOCnkxL0tCUXdN
    RW1BMEZuTTJaNDNYbGNpaDBhOXEzckd5MHpiYllXcjNoV0ZFb0NkbDlxekgrOGNEcXU5bDZyWTgK
    WHdVeFhzSnFIRXgvYnpuV2FGRkhQZz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K