apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: kubernetes.io/tls
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWc4Q0ZGWUdzeVl3T1F3WWg4T2JX
    K1BxWXhKUExGekdNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1GQXgKQ3pBSkJnTlZCQVlUQWtsTU1ROHdE
    UVlEVlFRSURBWkpjM0poWld3eEVqQVFCZ05WQkFjTUNVcGxjblZ6WVd4bApiVEVjTUJvR0ExVUVB
    d3dUTXpRdU1UWTFMalEwTGpjMExtNXBjQzVwYnpBZUZ3MHlNekV5TXpFeE5EQTRNVGRhCkZ3MHlO
    REF4TXpBeE5EQTRNVGRhTUZBeEN6QUpCZ05WQkFZVEFrbE1NUTh3RFFZRFZRUUlEQVpKYzNKaFpX
    d3gKRWpBUUJnTlZCQWNNQ1VwbGNuVnpZV3hsYlRFY01Cb0dBMVVFQXd3VE16UXVNVFkxTGpRMExq
    YzBMbTVwY0M1cApiekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFO
    SHNyOXRlaFMrTmhEMWhpL0RnClU1K1pEc3NjOTlCV21ic2xmWm8vSUJHU1hJUVV6dXJYa3NUMWZV
    aWFKeDk5N3hxQzRHUW9yeUVYVWdmL0hkMDEKTDdJL0o4TVFMK3p4ZUNrVSsxcms2QTVqYWp4STFo
    SHF1U1FhS3lSQkFXOWRyaWtTbExhZUZKTmZPT04yMDZIbgpGUkN0MTRzekVpN1JNYmhqKy9zdmNH
    SjhMdlBqNk54dW8zckhQYjJVV3NlK3IrRTV3N25IN0pxL3RJNkVJblFYCk10S25JeWFnUHQ2NWNY
    dlFmRXpwcmtGeEp3blBRRGpMWndUWWhSWE1qVG1YUHRaKzZQWFVqWFNLTndFYXJ5UHQKZzBieDFL
    MzNjbmMyZHplSC81bmJHQy9qYzE1T0djN3lMM3dnQXg0VHdOY0Y1d3hxcHJJdnNhR0Y5MU5DekdX
    cgpKaUVDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFYemthMnlMdjlRcHhyTWVzaG4y
    c2NFN2o1SE5zCm40OHY2dGs4aWF2eVpnaG5hQXBQeUVuMXBxT1JDSm9OR2FndGljcGEzeUJwbXdU
    VnAvQzBXajl1Sm9zR1RiL2cKa0pMSFZ0cnpwUU1yRFFuQ2E0NFM4dnkxMGNkTnRQN1p6NUEzNXFB
    UjE0MFJERWcvbnFzWFAxM0pIT0RvZjFvdgpSbXpYS2dReFkveUJaR3djSzNTSDBoWUJRQ1ErMEI5
    Z0xkK3djK3pZRzIxQXRvRVlEK3BJQlRzU1VaQ2haZFUrCkRZb3JXYkh4dkhKZkppaGl6MkphNUhQ
    b1VLWm5wYlhvZlZvL3R4MWtnRWtKSWZacGI4ekhteDk3R0krUWFXS2oKem0vUVIzZ01uWW85Ympq
    NjlnMWVlazEvejFGdExvVkphL2REckNRam5kd3dKT3h2MUJxM0JOVXA1QT09Ci0tLS0tRU5EIENF
    UlRJRklDQVRFLS0tLS0K
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktrd2dnU2xBZ0VBQW9JQkFRRFI3Sy9iWG9VdmpZUTkKWVl2dzRGT2ZtUTdMSFBmUVZwbTdK
    WDJhUHlBUmtseUVGTTdxMTVMRTlYMUltaWNmZmU4YWd1QmtLSzhoRjFJSAoveDNkTlMreVB5ZkRF
    Qy9zOFhncEZQdGE1T2dPWTJvOFNOWVI2cmtrR2lza1FRRnZYYTRwRXBTMm5oU1RYempqCmR0T2g1
    eFVRcmRlTE14SXUwVEc0WS92N0wzQmlmQzd6NCtqY2JxTjZ4ejI5bEZySHZxL2hPY081eCt5YXY3
    U08KaENKMEZ6TFNweU1tb0Q3ZXVYRjcwSHhNNmE1QmNTY0p6MEE0eTJjRTJJVVZ6STA1bHo3V2Z1
    ajExSTEwaWpjQgpHcThqN1lORzhkU3Q5M0ozTm5jM2gvK1oyeGd2NDNOZVRobk84aTk4SUFNZUU4
    RFhCZWNNYXFheUw3R2hoZmRUClFzeGxxeVloQWdNQkFBRUNnZ0VBQUlpN0pYTTdEbGlKQ2U3VXhk
    V1V5SkpNc1ZML1llMGg0Y3R6cE8zNkZaV0UKdGs3b3BZejRTWFZNNFh6S1FmWFBQa3VZY0VUazFD
    TGM0bGZrS3YxWitNcEFDZW1QMHZJUURQYUUxVmRyMDRYRQpGcy9RalFrd3BCbnUyVk1UYlFzNXpB
    OGU0ZEJWSEk2OGtEUUkvREkrcXcvK3JDSnlkd09vdXpmUXRaVTF0TDVICmtITzY4Y3lMOEUxKzc4
    UTdURkEzV2c4SUluSklYZVV1ZkxobWx2SkF5d1JrR3ZGcnhZdjhtdEIvOWI2TEFTTnkKdlN4czd3
    NzNXaGJXZGwzL0hoR252Yjg0dzRUQW11QnZRT1hXbC9EUEwvbWduaFkwUGhZMWxReWZacXAza2pv
    TwozRGVTazhYWDZxMkFZQnNvRm5iL3k5dXkxNktNS3hnOHVrbVNIV3lmMXdLQmdRRCt1VjJBZGZx
    ZlBCMlhiZG9SClFZT2h0T1FFOW05OTBIcVZacGZjaU43TmFQQjhvRy9aaGp0Q3d4UXdLRVh4Tk5Z
    VENsbUs2d0FQeUxJbklRdlQKT0Qvdi96V0FuZ3ArZ05KRVYrZUwwOEVyRUhaRkpLc1F6Q0FDTVJp
    dEtndDdzTmJwSFkrRFpmZExZcERIbzNzWgpEaHlwTHZ5b1FVL3hsTTZwL29KRklkVDdXd0tCZ1FE
    UytkLzUwaGdQY00rbS95SUFUS3BwajExSnZ2ek8wU0R6CmNyZzRWNVdwdmN5U3Q2aWtBTnpsVTdr
    NmpEVGV6UU11cDRJd044aG0yT1l4VDhLdk5Mdzd0Wmo2YmtHREpVSW8KMXpiVkV5N1RYZUZwaTI4
    WFJLUlp5bkdPWFpjTDBMRTFRQzdLdUdMLzRMZGdYMGxwVkI2Mitva09KV0tLRzcrYgpuRzJjRWtx
    cE13S0JnUURBaWxrVSt4amdPRTZkNGhsTnBkbmI1NkhiNW5OTUJNUkVIZko0YnJVTFMyRk1zdkVZ
    CjJZLzkzUHRyazJXYTk3ZEJXVGRwL0V4bG9leVlDekNuRGdPMlk1Q0xrZXFZeU1NbmlkS3FMUHY4
    azByeTVNNngKdWJvUUxoQmJCRWI5emlRRXZhVjNTeUhzUjZyc1hMUjFzZWNVTTBJajVJcUxMMUl2
    eVFPclFmRjl0UUtCZ1FDKwpSZ0dNSzhEclhCRExTZHArYnFaYW9hTysrUExFQzdRdUc4NnRjY0JX
    NEFoNllnMUVMRXNNd0orVGdCUEd4UnNUCm5wczVwWFdsM0FSdmdNSFNoanNsbHJnclUvamRzR0tr
    dHNTTEVzdnVjUUwwejM0WGZCN0ZwR0VaeHFxTlMyQW0KNklYSzZ0VE9kUHF0ZmdLVmJmcHRpRExI
    Z1V3SHh0TGVJd3h2NzhkS0pRS0JnUUM5RkZmQnBIZGJPazFyYk9MOQpDa1JoOFNXdFdMZGhpTTNz
    SFoySWIwQlhMaVZ4ZDB5U0lmSmZvZnIwbTNHVXBRTUt2TndYYVBJbUJBYThzcnJyClhINExxcWJj
    K0oxTlBnTnQzbUU4UEhYU0FVdUJ4N1lpYlhPdU1DNlJFNUVrYVlaQzhudnZGYkhlMk1WV2lmVWoK
    UzlMRUwxaUkyK1pseVB1TnpkMmZDNXZad1E9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==